# Generated by Django 5.0.6 on 2025-12-16 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVerity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala Chai'), ('GN', 'Ginger Chai'), ('KS', 'Kasir Chai'), ('PL', 'Plain Chai'), ('EL', 'Elichi Chai')], max_length=2)),
            ],
        ),
    ]
